# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Aodo0BqZL_vJR_iUa98tJl866723ycm
"""

!pip install pandas numpy matplotlib seaborn scikit-learn nltk

!pip install transformers deep-translator

import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

nltk.download('stopwords')
from nltk.corpus import stopwords

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("medquad.csv")
df = df[['question', 'answer', 'focus_area']]
df.dropna(inplace=True)

print("Dataset Shape:", df.shape)
df.head()

plt.figure(figsize=(10,5))
df['focus_area'].value_counts().head(10).plot(kind='bar')
plt.title("Raw Data: Top 10 Diseases Distribution")
plt.xlabel("Disease")
plt.ylabel("Number of Questions")
plt.show()

df['question_length'] = df['question'].apply(len)

plt.figure()
sns.histplot(df['question_length'], bins=30)
plt.title("Before Preprocessing: Question Length Distribution")
plt.xlabel("Characters")
plt.ylabel("Frequency")
plt.show()

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z ]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_question'] = df['question'].apply(clean_text)

print("BEFORE:")
print(df['question'].iloc[0])

print("\nAFTER:")
print(df['clean_question'].iloc[0])

df['clean_length'] = df['clean_question'].apply(len)

plt.figure()
sns.histplot(df['clean_length'], bins=30, color='green')
plt.title("After Preprocessing: Clean Question Length")
plt.xlabel("Characters")
plt.ylabel("Frequency")
plt.show()

df['manual_label'] = df['focus_area']

def emergency_label(text):
    text = str(text).lower()

    keywords = [
        "chest pain", "bleeding", "breathless",
        "unconscious", "fainting", "seizure",
        "stroke", "heart attack"
    ]

    for word in keywords:
        if word in text:
            return "Emergency"

    return "General"

# Apply on your dataset (IMPORTANT: column name check karo)
df['intent'] = df['question'].apply(emergency_label)

# Check output
df[['question', 'intent']].head()

y = df['intent']

df['intent'].value_counts()

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['clean_question'])
y = df['focus_area']

print("TF-IDF Matrix Shape:", X.shape)

plt.figure(figsize=(6,6))
plt.spy(X[:100], markersize=1)
plt.title("TF-IDF Sparse Matrix (First 100 Samples)")
plt.show()

#Text preprocessing (LABEL WORD LEAKAGE REMOVAL)
stop_words = set(stopwords.words('english'))
label_words = ['diabetes', 'cancer', 'heart', 'asthma', 'lung', 'eye', 'glaucoma']

def clean_text(text):
    text = text.lower()
    for lw in label_words:
        text = text.replace(lw, '')
    text = re.sub(r'[^a-z ]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_question'] = df['question'].apply(clean_text)

# 6 TF-IDF Feature Extraction (strict settings)
vectorizer = TfidfVectorizer(
    max_features=6000,
    ngram_range=(1,2),
    min_df=5,
    max_df=0.9
)

X = vectorizer.fit_transform(df['clean_question'])
y = df['manual_label']

# 7 Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# 8. Model training
model = LogisticRegression(
    max_iter=3000,
    class_weight='balanced',
    C=0.5
)

model.fit(X_train, y_train)


# 9. Prediction & accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Final Test Accuracy:", round(accuracy * 100, 2), "%")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", round(accuracy*100, 2), "%")

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(4,3))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=["Emergency", "General"],
            yticklabels=["Emergency", "General"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,        # numbers show karega
    fmt='d',
    cmap='Blues',
    linewidths=0.5
)

plt.title("Confusion Matrix Heatmap")
plt.xlabel("Predicted Labels")
plt.ylabel("Actual Labels")
plt.show()

print("Classification Report:\n")
print(classification_report(y_test, y_pred))

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

from google.colab import files

files.download("model.pkl")
files.download("vectorizer.pkl")

